### PR TITLE
Record previous searches

### LINKED ISSUE #12: Record previous searches
Add a search log somewhere on the page that shows the last 3 - 5 search logs, including the weather (at the time of search).
Something like the following:

- New York 17.36°C, (Tues) 12 Oct 2021
- Delhi 30°C, (Tues) 12 Oct 2021
- New York 12.36°C, (Tues) 12 Oct 2021

You can save this data in the local storage, you don't need to make an actual Database

### PR DESCRIPTION
**Pull request by ShiviPro**
## Summary
This PR renovates the search functionality as well as stores the search history in Local Storage.

## Details
This is PR 1 as we discussed in #12. 
Me and @Tanmay000009 have added the search functionality to work on both button press, and `Enter`(Return) keypress.
Also we've stored the most recent 5 searches made by the user in the local storage, while checking if the current search is the same as the most recent search (in which case, we don't store it).

## Related issues
 - This resolves #12.
 - This issue can also be used as an enhancement for issue #6 as discussed in issue #12.

### CODE REVIEW

**Comment by khattakdev** [comment]
@ShiviPro @Tanmay000009 I see you folks are using `localStorage` but the data you save is never rendered on the screen.

**Comment by Tanmay000009** [comment]
Hey @khattakdev, yes you are correct.
So as we discussed in #12, we'll be making 2 PRs, so this is the first one.
And 2nd one will be made after all of the major UI changes have been implemented as mentioned in other issues.

**Comment by ShiviPro** [comment]
Hey @khattakdev, I've resolved the merge conflicts regarding this PR.
I've used the dotenv npm package as standard here.
Kindly merge this, so that we can start working on the second PR of this as discussed in #12.

**Comment by quachtridat** [comment]
@ShiviPro you can choose to exclude part of changes on your local repo and commit + push only those changes that are necessary for the purpose of this pull request. `dotenv` will continue to exist in your local repo, and you can use that as you want. It can be done using interactive `git add` (and maybe some `git stash` to help save your code locally). Feel free to hit me up and I can tell more what I mean.

**Pull request merged**
