### PR TITLE
Graph for weather forecast

### LINKED ISSUE #9: Graph of weather forecast
We can show a graph of weather forecast to user for upcoming 10 days for a particular location

Edit : its for upcoming 7 days

- We can also show weather for past 5 days ,so user can see how weather is changing if this is something looks reasonable for user to know  (would appericiate other people views on this one)

### PR DESCRIPTION
**Pull request by atharmohammad**
Closes #9

### CODE REVIEW

**Comment by khattakdev** [comment]
@atharmohammad You might be already working on this but we need to use Axios eventually. I noticed you installed the package but haven't used it anywhere

**Comment by khattakdev** [comment]
@atharmohammad what issue if you can remind me, please. Are you talking about the code repetition issue?

**Comment by khattakdev** [comment]
> Yes , you suggested to make a function using axios customizing end point arguments .

Totally up to if you want to fix it in this PR or just go with fetch for now but I would suggest you to leave the repetition part for another PR and focus only on one task for now. You can then make a new PR for refactoring later.

**Comment by atharmohammad** [comment]
Hey @khattakdev  can we use typescript as well

**Comment by khattakdev** [comment]
> Hey @khattakdev can we use typescript as well ?

I would **not** encourage you to use it since the project is JavaScript-based.

**Comment by atharmohammad** [comment]
> > Hey @khattakdev can we use typescript as well ?
> 
> I would **not** encourage you to use it since the project is JavaScript-based.

since @Hemansh31  has already made some changes using typescript ,so to not waste time by waiting for him to convert these changes to javascript we will continue from here on using javascript. And if time persists we will convert those changes to js before final review

**Comment by atharmohammad** [comment]
@khattakdev work is done . can you please review it

**Comment by atharmohammad** [comment]
@khattakdev  Our work is done , please review it . Only things left is to provide graph component latitude and longitude and it will give you various visualisation of that location. this thing will be done after the fellows who are doing work on map as they are fetching lattitude and longitude . so i will raise issue for it and we will resolve that issue afterwards

**Pull request merged**
